### ISSUE TITLE
Problem with loading the pre-trained model

### ISSUE THREAD

**Issue by gaphex** [pender/chatbot-rnn#3]
Hi!
I was trying to run the pre-trained model you have provided and ran into an error.
Below is the full traceback
This might be a tensorflow compatibility problem, however you have not stated which version were you using to train it.
I used:
Ubuntu 16.04
Python 2.7.12
Tensorflow 0.12
CUDA 8.0
GeForce GTX 1080

```
$ python2 chatbot.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
Creating model...
WARNING:tensorflow:From /home/aphex/Projects/chatbot-rnn/model.py:168 in __init__.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /home/aphex/Projects/chatbot-rnn/model.py:183 in __init__.: merge_all_summaries (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge_all.
WARNING:tensorflow:From /home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/ops/logging_ops.py:264 in merge_all_summaries.: merge_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 6.98GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
WARNING:tensorflow:From chatbot.py:70 in sample_main.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Restoring weights...
W tensorflow/core/framework/op_kernel.cc:975] Not found: Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:975] Not found: Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:975] Not found: Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:975] Not found: Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:975] Not found: Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:975] Not found: Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
Traceback (most recent call last):
  File "chatbot.py", line 301, in <module>
    main()
  File "chatbot.py", line 35, in main
    sample_main(args)
  File "chatbot.py", line 74, in sample_main
    saver.restore(sess, model_path)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1416, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
	 [[Node: save/RestoreV2_13/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_36_save/RestoreV2_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_11', defined at:
  File "chatbot.py", line 301, in <module>
    main()
  File "chatbot.py", line 35, in main
    sample_main(args)
  File "chatbot.py", line 71, in sample_main
    saver = tf.train.Saver(net.save_variables_list())
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1028, in __init__
    self.build()
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1058, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 652, in build
    restore_sequentially, reshape)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 386, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 225, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2371, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aphex/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1258, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "rnnlm/multi_rnn_cell/cell_1/gru_cell/gates/weights" not found in checkpoint files models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]
	 [[Node: save/RestoreV2_13/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_36_save/RestoreV2_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

**Comment by gaphex** [comment]
I was able to fix that by installing Tensorflow==0.12.1 (was 0.12.0) with pip. Closing, please consider creating a requrements.txt with a particular version of the dependency.
