### ISSUE TITLE
reddit_parse error

### ISSUE THREAD

**Issue by DSMJR** [pender/chatbot-rnn#51]
`Reading from reddit_data\RS_2008-01.bz2
Traceback (most recent call last):
  File "reddit_parse.py", line 259, in <module>
    main()
  File "reddit_parse.py", line 37, in main
    parse_main(args)
  File "reddit_parse.py", line 87, in parse_main
    args.comment_cache_size, subreddit_dict, substring_blacklist, subreddit_whitelist, substring_blacklist)
  File "reddit_parse.py", line 105, in read_comments_into_cache
    subreddit_whitelist, substring_blacklist):
  File "reddit_parse.py", line 169, in post_qualifies
    body = json_object['body']
KeyError: 'body'
`
I'm on windows with python 3.6.7.

**Comment by DSMJR** [comment]
Made my own data parser.
