### ISSUE TITLE
Unable to run chatbot.py.  Throwing error on tensorflow

### ISSUE THREAD

**Issue by vinodk333** [pender/chatbot-rnn#54]
C:\chatbot-rnn-master>python chatbot.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatbot.py", line 4, in <module>
    import tensorflow as tf
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Comment by DSMJR** [comment]
What tensorflow and python version do you have?

**Comment by vinodk333** [comment]
Python 3.7.1 (anaconda 2018.12)
tensorflow-gpu-1.13.0rc2

**Comment by DSMJR** [comment]
tensorflow is not compatible with python 3.7. I recommend you switch to python 3.6.

**Comment by vinodk333** [comment]
Downgraded to Python 3.6.8.  Still same error.

**Comment by vinodk333** [comment]
Pls igore.  Issue is resolved when I uninstalled tensorflow-gpu and replaced with the CPU version.  My system have GPU though.

**Comment by DSMJR** [comment]
I personally do not have that much experience with the gpu version. Did you follow the steps here?
https://www.tensorflow.org/install/gpu

**Comment by DSMJR** [comment]
Did you add it to your path?

**Comment by DSMJR** [comment]
And if that doesn't help then you might want to uninstall and reinstall everything to make sure you don't have any conflicting packages.

**Comment by vinodk333** [comment]
Yes, tried all those, still no luck.  It was working fine earlier, need to troubleshoot further.

**Comment by DSMJR** [comment]
Ok, good luck to you.

**Comment by ColderCube** [comment]
getting the same error
idk what to do help me
thank you!

**Comment by saran-gangster** [comment]
you should uninstall your current tensorflow version "pip uninstall tensorflow"
then install tensorflow version 1.4.0 "pip install tensorflow==1.4.0"

**Comment by saran-gangster** [comment]
you don't have CUDA see [here](https://stackoverflow.com/questions/50622525/which-tensorflow-and-cuda-version-combinations-are-compatible)
