### ISSUE TITLE
Even the checkpont file is in the correct directory it is not identifying it

### ISSUE THREAD

**Issue by stijojoseph** [pender/chatbot-rnn#62]
Traceback (most recent call last):

  File "<ipython-input-1-51a4d05d857e>", line 339, in <module>
    main()

  File "<ipython-input-1-51a4d05d857e>", line 40, in main
    sample_main(args)

  File "<ipython-input-1-51a4d05d857e>", line 62, in sample_main
    model_path, config_path, vocab_path = get_paths(args.save_dir)

  File "<ipython-input-1-51a4d05d857e>", line 55, in get_paths
    raise ValueError('Checkpoint not found in {}.'.format(save_dir))

ValueError: Checkpoint not found in models/reddit.

@julien-c @julien-c

**Comment by saran-gangster** [comment]
i am also getting the same issue help me

**Comment by saran-gangster** [comment]
bro read the full readme file you  will get the amswer

**Comment by saran-gangster** [comment]
do you train it

**Comment by boboyoyo7** [comment]
up @stijojoseph  ! Did you solve this issue ?
@saran-gangster the model is pre-trained

**Comment by boboyoyo7** [comment]
up @stijojoseph  ! Did you solve this issue ?
@saran-gangster the model is pre-trained

**Comment by saran-gangster** [comment]
I solved the issue

**Comment by saran-gangster** [comment]
You should just download the [weights](https://drive.google.com/uc?id=1rRRY-y1KdVk4UB5qhu7BjQHtfadIOmMk&export=download) and keep it into the models directory
